name: Deploy Laravel Project to cPanel

on:
  push:
    branches:
      - main # Deploy when pushing to the main branch

jobs:
  deploy:
    name: Deploy Laravel Project
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up PHP
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Adjust PHP version based on your project's requirements
        tools: composer

    # Step 3: Install Composer dependencies
    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    # Step 4: Deploy files to cPanel via FTP
    - name: Deploy to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.5.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        local-dir: ./ # Adjust this if your project is in a subdirectory
        server-dir: ${{ secrets.REMOTE_PATH }}

    # Step 5: Clear Laravel Cache and Configurations
    - name: Clear Laravel Caches and Configurations
      run: |
        php artisan cache:clear
        php artisan config:clear
        php artisan route:clear
        php artisan view:clear
